.\" Process this file with
.\" groff -man -Tascii anamnesis.1
.\"

.TH ANAMNESIS 1 "DECEMBER 2010"

.SH NAME

Anamnesis \- clipboard history manager


.SH SYNOPSIS

.B anamnesis
[options]


.SH DESCRIPTION

.B Anamnesis
is a clipboard manager. It stores all clipboard history and offers
an easy interface to do a full-text search on it.


.SH OPTIONS


.TP
.B --version
show program's version number and exit

.TP
.B -h, --help           
show this help message and exit

.TP
.B --start              
starts anamnesis daemon

.TP
.B --stop               
stops anamnesis daemon

.TP
.B --restart            
restarts anamnesis daemon

.TP
.B -b, --browser        
opens anamnesis browser with clipboard history

.TP
.B --cleanup
optimize database and limit the number of elements

.TP
.B -l N, --list=N       
prints the clipboard history last N values

.TP
.B --filter=KEYWORDS    
use keywords to filter the clips to be listed

.TP
.B -a CLIP, --add=CLIP  
adds a value to the clipboard

.TP
.B --remove=ID_TO_REMOVE
removes the clipboard element with the given id

.TP
.B --brief
print only a brief version of long clipboard elements


.SH EXAMPLES

  Starts the graphic user interface:
      anamnesis --browser

  Starts the anamnesis daemon:
      anamnesis --start

  Stops the anamnesis daemon:
      anamnesis --stop

  List the last 20 clipboard items:
      anamnesis --list=20

  List the last 5 items in the clipboard the has the keywords 'my' and 'search':
      anamnesis --list=5 --filter="my search"

  Adds a clipboard item (same as copying to the clipboard if the daemon is running):
      anamnesis --add="hello, clipboard!"


.SH DEPENDENCIES

* python-xdg
* python-gtk2
* sqlite3


.SH CONFIGURATION

Anamnesis will search for configuration files in the $XDG_DATA_DIRS and
$XDG_CONFIG_HOME directories. It defaults to:
 
   /usr/share/anamnesis/anamnesis.cfg
   ~/.config/anamnesis/anamnesis.cfg


.SH AUTHOR

Written by Fabio Guerra <fabiowguerra@users.sourceforge.net>

Bugs should be reported on the project page:
  https://sourceforge.net/projects/anamnesis/

